name: rythmify

services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: rythmify_backend
    restart: unless-stopped
    env_file:
      - ../environments/.env
    ports:
      - "8080:8080"
    networks:
      - rythmify_network
    volumes:
      - ../../backend:/app
      - /app/node_modules

networks:
  rythmify_network:
    external: true
    name: rythmify_rythmify_network
